# Copyright 2023-2024 The Regents of the University of California
# released under BSD 3-Clause License
# author: Kevin Laeufer <laeufer@berkeley.edu>


[workspace]
resolver = "2"
members = ["dang", "shucks"]
default-members = ["dang"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"
authors = ["James Connolly <jimmy@1024bees.com>"]
description = "GDB for pre-silicon "
repository = "https://github.com/1024bees/dang"
keywords = ["vcd", "fst", "waveform", "wavedump"]
license = "MIT"

[workspace.dependencies]
gdbstub = "0.7.6"
gdbstub_arch = "0.3.0"


[profile.release]
debug = true
