[alias]
# Quiet test alias
qt = "test --quiet"

[env]
PYO3_STATIC = "1"
PYO3_PYTHON_VERSION = "3.10"
PYTHON_INCLUDE_DIR = "/abs/path/to/my_build_dir/Include"
PYTHON_LIB_DIR = "/abs/path/to/my_build_dir"
# Suppress env_logger output during tests
RUST_LOG = "error"
